version: '3'
services:
  db:
    image: postgres:9.6.8-alpine
    ports:
      - 5431:5432
  web:
      build: .
      ports:
        - "80:3000"
      environment:
        - RAILS_ENV=docker
      depends_on:
        - "db"
      command: >
          bash -c "sleep 3 ;
          bundle exec rake db:setup ;
          bundle exec rake db:migrate ;
          rails s"